spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_boook_rest
    username: root
    password: rootroot
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: kKJ%gi7$bjg@buBJn
  expiration: 330000

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB # by size
  file:
    name: /Users/narekgalstyan/Documents/IdeaProjects/restexample/log/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.example: info

cb:
  url: https://cb.am/latest.json.php